### ISSUE TITLE
Need to incorporate last modification, and time-of-insert into our public database

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-harvest#11]
These are required so that we can decide when to make incremental updates.

**Comment by jtyzzer** [comment]
Insert and update triples added to publication-creation code.

**Comment by qjhart** [comment]
@jtyzzer is there a pull request associated  with this?

**Comment by jtyzzer** [comment]
@qjhart Let's coordinate this at our 2:00.

**Comment by jtyzzer** [comment]
Quinn added these triples in his most recent round of changes.
