### ISSUE TITLE
Author / Publication deletion

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-harvest#12]
We need the commands to completely delete authors, publications, and relationships.  These need to be inplace for CDL updates.

**Comment by jtyzzer** [comment]
Expressed as an ERD, the User, Authorship, and Publication relationships are: USER -|--|< AUTHORSHIP >|--|- PUBLICATION

1. USER -|--|- AUTHORSHIP -|--|- PUBLICATION (1:1, 1:1)
User is sole author of a single publication
a. Deleting USER: Delete USER, delete AUTHORSHIP, delete PUBLICATION
b. Deleting AUTHORSHIP: delete AUTHORSHIP, delete USER, delete PUBLICATION
c. Deleting PUBLICATION: delete PUBLICATION, delete AUTHORSHIP, delete USER

2. USER -|--|- AUTHORSHIP >|--|- PUBLICATION (1:1, M:1)
User authored only one publication on which they're a coauthor
a. Deleting USER: Delete USER, delete AUTHORSHIP
b. Deleting AUTHORSHIP: delete AUTHORSHIP, delete USER
c. Deleting PUBLICATION: delete PUBLICATION, delete AUTHORSHIPs, delete USER

3. USER -|--|< AUTHORSHIP -|--|- PUBLICATION (1:M, 1:1)
User authored many monographs
a. Deleting USER: Delete USER, delete AUTHORSHIPs, delete PUBLICATION
b. Deleting AUTHORSHIP: delete AUTHORSHIP, delete PUBLICATION
c. Deleting PUBLICATION: delete PUBLICATION, delete AUTHORSHIP

4. USER -|--|< AUTHORSHIP >|--|- PUBLICATION (1:M, M:1)
User authored many publications, publication has many authors
a. Deleting USER: Delete USER, delete AUTHORSHIP
b. Deleting AUTHORSHIP: delete AUTHORSHIP
c. Deleting PUBLICATION: delete PUBLICATION, delete AUTHORSHIP

**Comment by jtyzzer** [comment]
Updating to include vcard off of document and additional AE-specific predicates.

**Comment by qjhart** [comment]
Examples 

- [ ] harvest delete {list of URLS}, ex. `harvest delete work:012345`

**Comment by qjhart** [comment]
Generic Data dellation



# Generic

CONSTRUCT {
   ?person ?prop ?val .
   ?child ?child_p ?child_o .
}
WHERE { graph ?g {
  bind(person:b78c058911b45047c56f3b5148381715 as ?person)
  ?person ?prop ?val ;
          .
  OPTIONAL {
    ?person (a|!a)+ ?child.
    ?child ?child_p ?child_o.
    filter(isblank(?child))
    FILTER NOT EXISTS {
      ?parent (a|!a)+ ?child.
      filter(isiri(?parent) && ?parent != ?person)
    }
  }
}}
