### ISSUE TITLE
Investigate Fuseki Insert timing issues.

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-harvest#13]
The new `harvest` script will allow users to import either one, or many, users at the same time.  However, the number of users added dramatically affects the timing of the inserts, in particular the inserts of the publications, `harvest update publications`.  Rather then the expected linear increase in time over the number of users (and therefore the number of publications), we get an expotential increase in time.  We need to track done the insert statement causing that.

**Comment by jtyzzer** [comment]
Per the analysis presented [here](https://docs.google.com/spreadsheets/d/1PHIWYMbfPiuVZG0TMrNxeKV34QMwFHkrzbQZFKOPCd0/edit?usp=sharing), the culprit--as anticipated--is publications.ru.

The steps taken in the analysis were:

1. Begin with an empty instance of AE
2. Populate the instance with experts one-at-a-time
    * Instantiate a shell variable with the list of users separated by spaces, e.g.:
        * `users="amoghimi benthem bougis...."`
        * Run this loop `for id in $users; do dc exec harvest harvest -v user --search=userId=$id --init --remove; done > sets_of_one.out`
3. Inspect the output file and sum and tally the timings for each user. This could be automated but I did it by hand via
    * grep -E '(cdl for ids|time=)' sets_of_one.out
4. Initialize the instance by cycling its containers
5. Unset the users variable and replace it with users in sets of two, e.g.:
    * `users="amoghimi,benthem bougis,chmkim daccache,dafrank...."`
6. Re-run the loop, outputting to a different file, e.g.:
    * `for id in $users; do dc exec harvest harvest -v user --search=userId=$id --init --remove; done > sets_of_two.out`
7. Inspect and tally the output as in step 3.
8. Initialize the instance by cycling its containers
9. Unset the users variable and replace it with users in sets of three, e.g.:
    * `users="amoghimi,benthem,bougis chmkim,daccache,dafrank...."`
10. Re-run the loop, outputting to a different file, e.g.:
    * `for id in $users; do dc exec harvest harvest -v user --search=userId=$id --init --remove; done > sets_of_three.out`
 11. Inspect and tally the output as in step 3.

**Comment by jtyzzer** [comment]
The user lists for further runs:

1. Individuals
`amoghimi benthem bougis chmkim daccache dafrank danhung dcs ergoman fkhorsan fzjenkin gangsun gmb ikisekka irdonisg jcgib jdemoura jdfbayo jkmason jmearles jrmerz jsmullin jsvander jzfan kkorn mahamed mgrismer mleite nnitin npan palarbi pourreza quinn ramram rhcastro rhzhang rkukreja sbsen sjmccorm spgentry sshong tjeoh vensberg ylhsieh ytakamur zlpan`

2. Pairs
`amoghimi,benthem bougis,chmkim daccache,dafrank danhung,dcs ergoman,fkhorsan fzjenkin,gangsun gmb,ikisekka irdonisg,jcgib jdemoura,jdfbayo jkmason,jmearles jrmerz,jsmullin jsvander,jzfan kkorn,mahamed mgrismer,mleite nnitin,npan palarbi,pourreza quinn,ramram rhcastro,rhzhang rkukreja,sbsen sjmccorm,spgentry sshong,tjeoh vensberg,ylhsieh ytakamur,zlpan`
3. Triples
`amoghimi,benthem,bougis chmkim,daccache,dafrank danhung,dcs,ergoman fkhorsan,fzjenkin,gangsun gmb,ikisekka,irdonisg jcgib,jdemoura,jdfbayo jkmason,jmearles,jrmerz jsmullin,jsvander,jzfan kkorn,mahamed,mgrismer mleite,nnitin,npan palarbi,pourreza,quinn ramram,rhcastro,rhzhang rkukreja,sbsen,sjmccorm spgentry,sshong,tjeoh vensberg,ylhsieh,ytakamur,zlpan`
