### ISSUE TITLE
An academic listed as non-academic

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-harvest#33]
Sangtae Kim appears as non-academic in both sandbox and gold. He is correctly identified as academic in rc, so the issue was fixed at some point.

**Comment by qjhart** [comment]
This issue is with the feed.  We should contact IAM for guideance  on fixing this.  In the meantime, I've added a note and a temporary fix for this, that can be run on all new imports. This will be in effect the next time the experts-data is pulled.
