### ISSUE TITLE
Coalesce Citation Information - page number

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-harvest#46]
If there are multiple citation sources, one thing that could be done would be to look from an ordered list, and continuously add in parameters.  For example, if the best citation didn't include a volume  number, but the next best did, then use the volume number from that citation source. 

@Vensberg will select a set of parameters to include in such a scheme.  To help, Elseveir provides some great tools for investigating citeproc citations.  [csl.mendeley.com](https://csl.mendeley.com) Specifically, the [Visual Editor](https://csl.mendeley.com/visualEditor/) can help identify these, for  example; using APA as an example, the following figure shows where the 'issue' parameter is used in the citation.

![image](https://user-images.githubusercontent.com/344953/119581905-639eaa80-bd78-11eb-8e8f-2f759056a3d3.png)

**Comment by qjhart** [comment]
We are starting with a very limited idea.  Coalescing ~page_number~.  Note, that I've discovered one example where a page number that is added, can't actually be added to the system, since it's so big, and so an idea for  this is we could coalesce on the minimum value in this case.  

There is on example [3538204] publication, that could benefit from a fixed page_number, but unfortunately there is only one datasource for  this.

[3538204]:https://oapolicy.universityofcalifornia.edu/viewobject.html?id=3538204&cid=1

**Comment by qjhart** [comment]
If we look at the source of all the pagination, then can see that although
    most best citations have pages, there are quite a few that get filled in
    with a later citation.

```sparql
  select ?best ?page  (count(*) AS ?CNT) WHERE {
    VALUES (?best ?p) {
      ("verified-manual" 1) ("epmc" 2) ("pubmed" 3)  ("scopus" 4)("wos" 5) ("wos-lite" 6)
      ("crossref" 7)  ("dimensions" 8) ("arxiv" 9)("orcid" 10) ("dblp" 11)  ("cinii-english" 12)
      ("repec" 13)  ("figshare" 14)  ("cinii-japanese" 15) ("manual" 16)  ("dspace" 17) }
  
    VALUES (?page ?p2) {
      ("verified-manual" 1) ("epmc" 2) ("pubmed" 3)  ("scopus" 4)("wos" 5) ("wos-lite" 6)
      ("crossref" 7)  ("dimensions" 8) ("arxiv" 9)("orcid" 10) ("dblp" 11)  ("cinii-english" 12)
      ("repec" 13)  ("figshare" 14)  ("cinii-japanese" 15) ("manual" 16)  ("dspace" 17) }
  
    ?work ucdrp:best_source ?best;
          ucdrp:pagination_source ?page;
          .
    #  filter( ?best != ?page)
  } group by ?best ?page  ?p ?p2 order by ?p ?p2   
```

This table is in order of preference of citation use.    


| best          | page          |  CNT |
|---|---|---|
| epmc          | epmc          | 2099 |
| epmc          | scopus        |   13 |
| epmc          | wos-lite      |    1 |
| epmc          | crossref      |   60 |
| epmc          | dimensions    |    7 |
| pubmed        | wos-lite      |    1 |
| scopus        | scopus        | 5274 |
| scopus        | wos-lite      |   97 |
| scopus        | crossref      |  336 |
| scopus        | dimensions    |  259 |
| scopus        | dblp          |    1 |
| scopus        | dspace        |    1 |
| wos-lite      | wos-lite      |  733 |
| wos-lite      | crossref      |   35 |
| wos-lite      | dimensions    |    2 |
| wos-lite      | manual        |    1 |
| crossref      | crossref      |   76 |
| crossref      | dimensions    |   32 |
| crossref      | dspace        |    1 |
| dimensions    | dimensions    |   18 |
| arxiv         | arxiv         |    3 |
| dblp          | dblp          |   47 |
| cinii-english | cinii-english |    2 |
| manual        | manual        |  129 |
| dspace        | dspace        |    4 |

**Comment by Vensberg** [comment]
Many citations have been improved with added pages. 
All the ones that I checked that are still missing pages have only the starting page listed in the citation. E.g. 
https://dev.experts.ucdavis.edu/work/3109768
https://oapolicy.universityofcalifornia.edu/viewobject.html?cid=1&id=3109768
@qjhart, if it is a big lift to allow a single page for pagination (and leave off the end page), let's leave it for 1.5
Some publications have lost abstracts, but that was expected since the sources were reprioritized. This will be addressed in the next increment of improving citations.
