### ISSUE TITLE
Non-PI Grant associations

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-harvest#52]
The grants_complete table includes non-PI roles as well.  This is not captured in the current grant query.  The roles are found in the `CS_EFFORT_COMMITMENT` table, which is joined on the awdext.UC_LOC_CD field. 

``` test 
, ec.EMPLOYEE_ID
    , per2.PERSON_NM AS "EffortCommittmentName"
    , ec.EMPLOYEE_ROLE_ID
    , ec.STATUS_CODE
``

We need a mapping of the ROLE_ID to VIVO Grant roles

**Comment by Vensberg** [comment]
UCD warehouse definitions
PI = Principal Investigator
OTHR = Other
COPI = Co-PI
KP  = Key Personnel
PLDR = Project Leader
PDIR = Program Director
CLDR = Core Leader

**Comment by Vensberg** [comment]
UCDWh: Co-PI 

VIVO
<owl:Class rdf:about="http://vivoweb.org/ontology/core#CoPrincipalInvestigatorRole">
<rdfs:label xml:lang="en">Co-Principal Investigator Role</rdfs:label>
<rdfs:subClassOf rdf:resource="http://vivoweb.org/ontology/core#InvestigatorRole"/>
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
Role of co-principal investigator of an Agreement (for example, a grant), who devotes a specified percentage of time and is considered key personnel.
</obo:IAO_0000115>
</owl:Class>

MIV: Co-Principal Investigator

**Comment by Vensberg** [comment]
UCDWh:  Project Leader

<owl:Class rdf:about="http://vivoweb.org/ontology/core#LeaderRole">
<rdfs:label xml:lang="en">Leader Role</rdfs:label>
<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000023"/>
<obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
A broad-ranging leader concept, from leading a small temporary committee to head of a large international organization.
</obo:IAO_0000112>
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A leadership role</obo:IAO_0000115>
</owl:Class>

MIV: unclear

**Comment by Vensberg** [comment]
UCDWh: pending

VIVO:
<owl:Class rdf:about="http://vivoweb.org/ontology/core#InvestigatorRole">
<rdfs:label xml:lang="en">Investigator Role</rdfs:label>
<rdfs:subClassOf rdf:resource="http://vivoweb.org/ontology/core#ResearcherRole"/>
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
A role in an Agreement (for example, a grant) as a named investigator or key personnel.
</obo:IAO_0000115>
</owl:Class>

MIV: Co-Investigator

**Comment by Vensberg** [comment]
Catch-all
<owl:Class rdf:about="http://vivoweb.org/ontology/core#ResearcherRole">
<rdfs:label xml:lang="en">Researcher Role</rdfs:label>
<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000023"/>
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
A role of conducting funded or unfunded research, sometimes linked to an Agreement.
</obo:IAO_0000115>
<obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
Examples of research can be seen at: http://www.ufl.edu/research/products/index.html. Note these may have been funded, but the research doesn't have to be funded. Also, the research may be linked to an Agreement (for example, a Grant), but does not need to be.
</obo:IAO_0000112>
</owl:Class>

or

<owl:ObjectProperty rdf:about="http://vivoweb.org/ontology/core#contributingRole">
<rdfs:label xml:lang="en">contributor</rdfs:label>
<rdfs:range rdf:resource="http://purl.obolibrary.org/obo/BFO_0000023"/>
<owl:inverseOf rdf:resource="http://vivoweb.org/ontology/core#roleContributesTo"/>
</owl:ObjectProperty>

MIV: Other (can't resolve down to Assistant Researcher, Collaborator, Instructor, Trainer)

**Comment by Vensberg** [comment]
From Whitney Cheung, OR;
•	Program Director – Often used interchangeably with “Principal Investigator” (PD/PI); the person responsible for the project or program if awarded.  
•	Key Personnel – Umbrella term for an investigator who will contribute / do work on / carry out the proposed project, part of the research team.  May also be referred to as a primary contributor or senior personnel.  Per NIH: “…individuals who contribute to the scientific development or execution of a project in a substantive, measurable way, whether or not they receive salaries or compensation under the grant…Consultants and those with a postdoctoral role also may be considered senior/key personnel if they meet this definition. Senior/key personnel must devote measurable effort to the project whether or not salaries or compensation are requested. "Zero percent" effort or "as needed" are not acceptable levels of involvement for those designated as Senior/Key Personnel.”
•	Core Leader – Investigator who is designated as the lead for a “core”, as a component/project in large multi-project proposals like center grants (e.g. Center ABC, with an Administrative Core, an Education Core, and two projects).  NIH refers to it as a “distinct, reviewable part…for which there is a business need to gather detailed information identified in the funding opportunity announcement”.
•	Project Leader – Investigator who is designated as the lead for a particular component within a multi-project proposal.  “Project” may be used interchangeably with “Core” as defined above.

Other resources for definitions
UC Contract & Grant Manual Chapter 1-500: Principal Investigator Guidelines
1-520 Leadership of a Sponsored Project
An essential qualification of the individual who proposes to head an extramurally supported research, training, or public service project is that he or she will personally participate in it to a significant degree. It is contrary to University policy, and is viewed with extreme disfavor by sponsoring agencies, to list as head of a project the name of an individual, however prestigious that person may be, who will contribute only a minimum or nominal portion of their own time and effort to the furtherance of the work. Within this basic qualification:
a.	The head of a research project is called a Principal Investigator. On occasion, he or she may have one or more Co-Principal Investigators who share with him or her responsibility for participatory conduct of the project.
b.	The head of a training or public service project may be also be called a Project Administrator or Project Director.
c.	The head of a program involving more than one project may be also be called a Program Administrator.

Cayuse SP – UC Davis Handbook for Department Contract & Grant Staff, Principal Investigators and Approvers

**Comment by qjhart** [comment]
I am using the following roles, and definitions: 

```ttl
  VALUES (?grant_role ?ucd_role ?vivo_role) {
    ("PDIR" ucdrp:GrantProgramDirectorRole vivo:LeaderRole)
    ("KP" ucdrp:GrantKeyPersonnelRole vivo:ResearcherRole)
    ("OTHR" ucdrp:GrantOtherRole vivo:ResearcherRole)
    ("PLDR" ucdrp:GrantProjectLeaderRole vivo:LeaderRole)
    ("COPI" ucdrp:GrantCoPrincipalInvestigatorRole vivo:CoPrincipalInvestigatorRole)
    ("PI" ucdrp:GrantPrincipalInvestigatorRole vivo:PrincipalInvestigatorRole )
    ("CLDR" ucdrp:GrantCoreLeaderRole,vivo:ResearcherRole)
    }

```

```ttl
ucdrp:GrantProgramDirectorRole
    a vivo:ResearcherRole ;
    rdfs:label "Program Director" ;
    ucdrp:abbrev "PDIR" ;
    .

ucdrp:GrantKeyPersonnelRole
    a vivo:ResearcherRole ;
    rdfs:label "Key Personnel" ;
    ucdrp:abbrev "KP" ;
    .

ucdrp:GrantOtherRole
    a vivo:ResearcherRole ;
    rdfs:label "Researcher" ;
    ucdrp:abbrev "OTHR" ;
    .

ucdrp:GrantProjectLeaderRole
    a vivo:ResearcherRole ;
    rdfs:label "Project Leader" ;
    ucdrp:abbrev "PLDR" ;
    .
ucdrp:GrantCoPrincipalInvestigatorRole
    a vivo:ResearcherRole ;
    rdfs:label "Co-Principal Investigator" ;
    ucdrp:abbrev "COPI" ;
    .
ucdrp:GrantPrincipalInvestigatorRole
    a vivo:ResearcherRole ;
    rdfs:label "PrincipalInvestigator" ;
    ucdrp:abbrev "PI" ;
    .
ucdrp:GrantCoreLeaderRole
    a vivo:ResearcherRole ;
    rdfs:label "Core Leader" ;
    ucdrp:abbrev "CLDR" ;
    .

```
